In [27]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 

In [28]:
df=pd.read_csv('diabetes.csv')

In [29]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [30]:
# importam modelul de Mashine Learning
from sklearn.neighbors import KNeighborsClassifier
#luam toate datele si impartim in doua coloana target
from sklearn.model_selection import train_test_split
#acuratetea modelului
from sklearn.metrics import accuracy_score

In [31]:
#Amestecam valorile coloanei pentru a prevedea toate cazurile
df=df.sample(frac=
             1)

In [32]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
198            4      109             64             44       99  34.8   
758            1      106             76              0        0  37.5   
138            0      129             80              0        0  31.2   
668            6       98             58             33      190  34.0   
622            6      183             94              0        0  40.8   
..           ...      ...            ...            ...      ...   ...   
389            3      100             68             23       81  31.6   
290            0       78             88             29       40  36.9   
715            7      187             50             33      392  33.9   
51             1      101             50             15       36  24.2   
575            1      119             44             47       63  35.5   

     DiabetesPedigreeFunction  Age  Outcome  
198                     0.905   26        1  
758                     0.197   26        0  
138                     0.703   29        0  
668                     0.430   43        0  
622                     1.461   45        0  
..                        ...  ...      ...  
389                     0.949   28        0  
290                     0.434   21        0  
715                     0.826   34        1  
51                      0.526   26        0  
575                     0.280   25        0  

[768 rows x 9 columns]

In [35]:
# transformam tabelul in matrici fara coloana target
X=df.drop(['Outcome'], axis=1).values
Y=df['Outcome'].values

In [36]:
X

array([[  4.   , 109.   ,  64.   , ...,  34.8  ,   0.905,  26.   ],
       [  1.   , 106.   ,  76.   , ...,  37.5  ,   0.197,  26.   ],
       [  0.   , 129.   ,  80.   , ...,  31.2  ,   0.703,  29.   ],
       ...,
       [  7.   , 187.   ,  50.   , ...,  33.9  ,   0.826,  34.   ],
       [  1.   , 101.   ,  50.   , ...,  24.2  ,   0.526,  26.   ],
       [  1.   , 119.   ,  44.   , ...,  35.5  ,   0.28 ,  25.   ]])

In [37]:
Y

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=42)

In [39]:
knn=KNeighborsClassifier()

In [40]:
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [41]:
Y_pred=knn.predict(X_test)

In [42]:
Y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [43]:
# calculam acuratetea
accuracy_score(Y_pred, Y_test)

0.65625

In [44]:
#avem nu cea mai buna acuratete, utilizam standartizarea datelor
from sklearn.preprocessing import StandardScaler

In [45]:
std=StandardScaler()

In [46]:
X_train_scaled=std.fit_transform(X_train)

In [47]:
X_test_scaled=std.transform(X_test)

In [48]:
knn.fit(X_train_scaled, Y_train)

KNeighborsClassifier()

In [49]:
Y_pred=knn.predict(X_test_scaled)

In [50]:
accuracy_score(Y_test,Y_pred)

0.734375